// This file is generated by Slice Machine. Update with care!

import BasicContent from './BasicContent';
import ImageGallery from './ImageGallery';

export {
	BasicContent,
	ImageGallery,
};

export const components = {
	basic_content: BasicContent,
	image_gallery: ImageGallery,
};
