'use client'

import Head from 'next/head'
import Link from 'next/link'
import { useLayoutEffect } from 'react'
import { runCanvasAnimation } from '../utils/canvas'
import { gsap } from 'gsap'

export default function Home() {
  useLayoutEffect(() => {
    let img = new Image()
    img.src = '/main.jpg'

    const { stop } = runCanvasAnimation(img)

    return () => stop()
  }, [])

  // useLayoutEffect(() => {
  //   gsap.fromTo(
  //     '.grayscale',
  //     {
  //       filter: 'grayscale(0)',
  //     },
  //     {
  //       filter: 'grayscale(1)',
  //       duration: 1,
  //       delay: 1,
  //     }
  //   )
  //   gsap.fromTo(
  //     '.overlay',
  //     { opacity: 0 },
  //     { opacity: 1, duration: 1, delay: 1 }
  //   )
  //   gsap.timeline()
  // }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-screen w-screen'>
        <canvas className='h-screen w-screen block fixed top-0 left-0 grayscale'></canvas>
        <div className='overlay h-screen w-screen bg-cyan-400 fixed z-10 mix-blend-multiply'></div>

        <div className='title fixed w-full top-0 flex justify-center z-10 bg-white'>
          <h1 className='text-8xl text-bold uppercase'>Studilaroche</h1>
        </div>

        <div className='links relative flex justify-center z-10 bg-white'>
          <Link
            href='/about'
            className='fixed top-[20%] left-[30%] rotate-12 bg-white px-2 uppercase text-lg'
          >
            About
          </Link>
        </div>
      </main>
    </>
  )
}
