'use client'

import Head from 'next/head'
import { useLayoutEffect } from 'react'
import styles from '../styles/Home.module.css'
import { runCanvasAnimation } from '../utils/canvas'

export default function Home() {
  useLayoutEffect(() => {
    let img = new Image()
    img.src = '/main.jpg'

    const { stop } = runCanvasAnimation(img)

    return () => stop()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='h-screen w-screen'>
        <canvas className='h-screen w-screen block fixed top-0 left-0 grayscale'></canvas>
        <div className='h-screen w-screen bg-orange-800 fixed z-10 mix-blend-screen'></div>

        <div className='relative flex h-full items-center justify-center z-10 '>
          <h1 className='text-8xl text-bold uppercase'>Studilaroche</h1>
        </div>
      </main>
    </>
  )
}
